name: docs

on:
  push:
    branches: [main]

# 👇 give the token write access to the repo
permissions:
  contents: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - run: pip install mkdocs-material mkdocstrings mkdocstrings-python pymdown-extensions
      - run: mkdocs build --strict

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: site
          publish_branch: gh-pages   
